### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JonLwJ** [DJSchaffner/aoe2de_patcher#9]
**Describe the bug**
Can't login to Multiplayer services

I've reverted back to original patch, gave me the error
Reverified files
Uninstalled and Reinstalled game
Uninstalled and Reinstalled Steam
Searched on AOE Forums for the error but to no solution

Is it maybe still attached to your program?

**Screenshots**
![Error-Failed Signin](https://github.com/DJSchaffner/aoe2de_patcher/assets/91917706/73a6c884-da2e-4ede-976f-4a2ac3522139)

**Comment by DJSchaffner** [comment]
Very strange error indeed. If you reinstalled the game already (just to be sure, maybe check the folder is empty after uninstalling) I wouldn't know how the error could be caused by the patcher. All it is doing, is replacing a few files in the AoE folder with the files from the selected version.

Sounds like you need to contact Microsoft support for this issue if it doesn't resolve itself.

Without knowing anything about this error, my best guess other than reinstalling would be to maybe clear the DNS cache. Maybe something got messed up there

**Comment by JonLwJ** [comment]
Sounds good, I'll try that. Yeah contacted them, still waiting for response

**Comment by JonLwJ** [comment]
So, it was my antivirus, firewall preventing connection after all. Silly mistake of not thoroughly checking. Thanks anyways for the reply!
